const USER_ROLES = {
  ADMIN: "ADMIN",
  SUPERADMIN: "SUPERADMIN",
  STUDENT: "STUDENT",
};

const TOKEN_TYPES = {
  USER_SESSION: "USER_SESSION",
  RESET_PASSWORD: "RESET_PASSWORD",
  USER_INVITATION: "USER_INVITATION",
};

export { USER_ROLES, TOKEN_TYPES };
